name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and deploy to gh-pages
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to gh-pages"
          git push origin gh-pages
